name: Buil NPM Package

# Runs build/test/publish for an NPM package
#
# Publishing is done purely by calling 'npm publish', all the configuration must be specified in the .npmrc file of the package
# Both NODE_AUTH_TOKEN and GITHUB_READ_PACKAGES_TOKEN are supported in .npmrc

on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        required: true
      working-directory:
        type: string
        required: true

    secrets:
      # Value for token used in .npmrc.
      # We define both NODE_AUTH_TOKEN and GITHUB_READ_PACKAGES_TOKEN environment variables with this value
      NODE_AUTH_TOKEN:
        required: false

# Ensure no two workflows of the same type (e.g. 2 PRs) are running at the same time
# FYI within a repo, no 2 workflows with the same group value would run concurrently;
# github.workflow is the name of the action, e.g. "Pull Requests"
concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      GITHUB_READ_PACKAGES_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0' # Specify the Node.js version you want to use
      #     registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          yarn install

      - name: Build
        run: |
          npm run build --if-present

      - name: Test
        run: |
          yarn test

      - name: Publish
        if: inputs.publish
        run: |
          npm publish

      - name: Update Version and Push
        if: inputs.publish
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # This also creates a tag which we ignore (don't push to the server) on purpose
          yarn version --patch
          git push

      # https://github.com/marketplace/actions/junit-report-action
      - name: Create Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: "junit.xml"
          annotate_only: true
          include_passed: false
          detailed_summary: true

      - name: Save Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: "junit-results--${{ github.event.repository.name }}--#${{ github.run_number }}"
          path: "junit.xml"
          if-no-files-found: ignore
