name: Handle PRs

on:
  workflow_call:
    secrets:
      DEVROCK_PIPELINE_UPLOAD_USER:
        required: true
      DEVROCK_PIPELINE_UPLOAD_PASSWORD:
        required: true
      NODE_AUTH_TOKEN:
        required: false

jobs:
  pr:
    uses: ./.github/workflows/build.yaml
    secrets:
      DEVROCK_PIPELINE_UPLOAD_USER: "${{ secrets.DEVROCK_PIPELINE_UPLOAD_USER }}"
      DEVROCK_PIPELINE_UPLOAD_PASSWORD: "${{ secrets.DEVROCK_PIPELINE_UPLOAD_PASSWORD }}"
      NODE_AUTH_TOKEN: "${{ secrets.NODE_AUTH_TOKEN }}"
    with:
        job-name: 'pull-request'
        checkout-ref: 'refs/pull/${{ github.event.number }}/head'
        # github.base_ref is the name of the branch, e.g. 'main'
        analyze-codebase-opts: '--baseBranch ${{ github.base_ref }}'
        comment-input: '${{ github.event.pull_request.body }}'