name: Build Custom Range

on:
  workflow_call:
    inputs:
      range:
        type: string
        default: "."
      publish:
        type: boolean
        default: true

jobs:
  custom-range:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
        job-name: 'custom-range'
        # github.ref is 'refs/heads/${branch}', e.g. 'refs/heads/main'
        checkout-ref: '${{ github.ref }}'
        # github.ref_name is (for manually triggered) the name of the branch, e.g. main
        analyze-codebase-opts: '+baseBranch ${{ github.ref_name }} +range ${{ inputs.range }}'
        publish: ${{ inputs.publish }}