name: Build Release View

on:
  workflow_call:
    inputs:
      artifactId:
        type: string
        required: true

jobs:
  unpublished:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
        job-name: 'build-release-view'
        # github.ref is 'refs/heads/${branch}', e.g. 'refs/heads/main'
        checkout-ref: '${{ github.ref }}'
        # github.ref_name is (for manually triggered) the name of the branch, e.g. main
        analyze-codebase-opts: '--baseBranch ${{ github.ref_name }} --buildArtifacts ${{ inputs.artifactId }} --allowReleaseViewBuilding true'
