name: Build Release View

on:
  workflow_call:
    inputs:
      artifactId:
        type: string
        required: true
    secrets:
      DEVROCK_PIPELINE_UPLOAD_USER:
        required: true
      DEVROCK_PIPELINE_UPLOAD_PASSWORD:
        required: true
      NODE_AUTH_TOKEN:
        required: false

jobs:
  unpublished:
    uses: ./.github/workflows/build.yaml
    secrets:
      DEVROCK_PIPELINE_UPLOAD_USER: "${{ secrets.DEVROCK_PIPELINE_UPLOAD_USER }}"
      DEVROCK_PIPELINE_UPLOAD_PASSWORD: "${{ secrets.DEVROCK_PIPELINE_UPLOAD_PASSWORD }}"
      NODE_AUTH_TOKEN: "${{ secrets.NODE_AUTH_TOKEN }}"
    with:
        job-name: 'build-release-view'
        # github.ref is 'refs/heads/${branch}', e.g. 'refs/heads/main'
        checkout-ref: '${{ github.ref }}'
        # github.ref_name is (for manually triggered) the name of the branch, e.g. main
        analyze-codebase-opts: '--baseBranch ${{ github.ref_name }} --buildArtifacts ${{ inputs.artifactId }} --allowReleaseViewBuilding true'
