name: Build Unpublished

on:
  workflow_call:
    secrets:
      DEVROCK_PIPELINE_UPLOAD_USER:
        required: true
      DEVROCK_PIPELINE_UPLOAD_PASSWORD:
        required: true

jobs:
  unpublished:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
        job-name: 'build-unpublished'
        # github.ref is 'refs/heads/${branch}', e.g. 'refs/heads/main'
        checkout-ref: '${{ github.ref }}'
        # github.ref_name is (for manually triggered) the name of the branch, e.g. main
        analyze-codebase-opts: '--baseBranch ${{ github.ref_name }} --detectUnpublishedArtifacts true'